# Generated by Django 2.2.2 on 2019-06-17 14:29

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=50)),
                ('short_desc', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=1000)),
                ('is_read', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('NOTIFICATION', 'NOTIFICATION'), ('NOTIFICATION_AND_EMAIL', 'NOTIFICATION_AND_EMAIL'), ('NOTIFICATION_EMAIL_AND_MESSAGE', 'NOTIFICATION_EMAIL_AND_MESSAGE')], default='NOTIFICATION', max_length=50)),
            ],
        ),
    ]
