# Generated by Django 2.2.2 on 2019-06-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sour_and_perky', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusertrophy',
            name='short_description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usertrophy',
            name='short_description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
