# Generated by Django 2.2.2 on 2019-06-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sour_and_perky', '0002_auto_20190617_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusertrophy',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='usertrophy',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
