# Generated by Django 2.2.2 on 2019-06-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sour_and_perky', '0003_auto_20190617_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalentry',
            name='text',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
    ]
