# Generated by Django 2.2.2 on 2019-06-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sour_and_perky', '0004_auto_20190617_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='desc',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='desc',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
    ]
