# Generated by Django 2.2.2 on 2019-06-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sour_and_perky', '0005_auto_20190617_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
