# Generated by Django 2.2.2 on 2019-06-17 20:17

import apps.sour_and_perky.models.common
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sour_and_perky', '0006_auto_20190617_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='author',
            field=models.ForeignKey(default=apps.sour_and_perky.models.common.first_user_id, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
