# Generated by Django 2.2.2 on 2019-06-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sour_and_perky', '0007_auto_20190617_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='avatar',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
