# Generated by Django 2.2.2 on 2019-07-01 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sour_and_perky', '0011_auto_20190701_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='channels',
            field=models.ManyToManyField(blank=True, related_name='titles', to='sour_and_perky.TitleChannel'),
        ),
    ]
