from .authentication import social_auth_urls
from .entry import EntryViewSet
from .event import EventViewSet
from .notification import NotificationViewSet
from .title import TitleViewSet
from .title_channel import TitleChannelViewSet
from .user import UserViewSet
from .user_trophy import UserTrophyViewSet
from .relations import relation_urls
